---
title: "Exploring civility in the Hansard"
author: "Alfonso M Arranz"
date: "4/23/2021"
output: html_document


---

```{r setup, include=FALSE}

library(tidyverse)
library(lubridate)

dta <- read_csv("/data/hansard/civility_data/civility_full_downloaded.csv", col_types = cols(.default = "c"))

dta <- dta %>% 
      mutate(year = year(dmy(date)),
         source = fct_explicit_na(fct_collapse(source, "Senate" = c("Senate", "SENATE"),
                               "House of Reps" = c("REPS", "House of Reps")), "Estimates and reports"))


knitr::opts_chunk$set(echo = FALSE, warning = FALSE)

```


```{r, echo = TRUE}


uncivil_nouns <-  c("disrespect", "incivility", "impoliteness")

civil_nouns <- c("civility", "politeness", "respect")

civil_adj <- c("respectful", "polite", "courteous")

uncivil_adj <- c("disrespectful", "discourteous", "uncivil", "impolite")
                   
all_terms <- c(uncivil_nouns, civil_nouns, civil_adj, uncivil_adj)  

names(all_terms) <- paste0("t_", all_terms)
                                    
term_groups <- list(uncivil_nouns, civil_nouns, civil_adj, uncivil_adj)    

names(term_groups) <- c("uncivil_nouns", "civil_nouns", "civil_adj", "uncivil_adj")

```



## Sources

```{r}

dta %>% 
  count(source)


```

```{r}
dta %>% 
  count(database)


```



## Term prevalence over time

```{r, cache = TRUE}
c_by_groups <- purrr::map(term_groups, ~stringr::str_count(dta$main_text,
                                                           cptools::bound_rx(.x)))


c_by_term <- purrr::map(all_terms, ~stringr::str_count(dta$main_text, 
                                                       cptools::bound_rx(.x)))

```


```{r, rows.print = 40}


cdf <- bind_cols(select(dta, source, party, year, main_text), c_by_term)

cdf %>% 
  pivot_longer(contains("t_"), names_to = "term", values_to = "occurrences") %>% 
  mutate(term = str_remove(term, "t_")) %>% 
  group_by(source, term) %>% 
  summarise(total_occurrences = sum(occurrences, na.rm = T))
  


```



```{r}
plot_df <- bind_cols(select(dta, source, party, year), c_by_groups) %>% 
  group_by(year, source) %>% 
  mutate(n_docs = n()) %>% 
  ungroup() %>% 
  pivot_longer(contains("civil"), names_to = "term", values_to = "occurrences") %>% 
  group_by(year, term, source) %>% 
  summarise(occurrence_prop = sum(occurrences)/n()) %>% 
  ungroup()

doc_labs <- dta %>% 
  group_by(source) %>% 
  summarise(total_docs = n())



```


```{r}

ggplot(plot_df) +
  geom_col(aes(x = year, y = occurrence_prop, fill = term)) +
  geom_text(aes(x = 1930, y = 12, label = paste0("n_docs = ", total_docs)), data = doc_labs) +
  facet_wrap(~source)




```



```{r}

cdf %>% 
  filter(year > 2000, source == "Senate") %>% 
  filter(t_respect > 0) %>% 
  slice_sample(n = 1) %>% 
  pull(main_text)
  


```

