---
title: "Australian coal Hansard statistics"
author: "Alfonso M Arranz"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: false
    df_print: paged
---

```{r, echo = FALSE}
pacman::p_load(readabs, tidytable, scales, stringr, forcats, purrr, ggplot2, lubridate, tibble, zoo)



early_prod_n_jobs <- fread.("coal_data/general_stats/auscoal_1913_1980_prod_n_workforce.csv")%>% 
  janitor::clean_names()

late_jobs <- fread.("coal_data/general_stats/ABS_coal_employees_series_A84602523V.csv")

industrial <- fread.("coal_data/general_stats/ABS_industrial_disputes_6321.0.55.001.csv")

main_eras <- c(1935, 1963, 2005)


population <- fread.("coal_data/general_stats/aus_total_pop.csv")


labour_force <- fread.("coal_data/general_stats/ABS_labour_detailed_6291.0.55.001.csv")%>% 
    mutate.(year = year(date))

trade <- fread.("coal_data/general_stats/ABS_trade_5368.0.csv") %>% 
    mutate.(year = year(date))


basic_add_ons <- list(labs(x = ""),
                    geom_vline(xintercept = main_eras, linetype = "dashed"))




knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, results = 'asis', cache.lazy = FALSE)

```


```{r}

simple_series_name <- function(str) {
  
  str %>% 
    str_remove_all("[^A-Za-z- ]") %>% 
    str_squish() %>% 
    str_extract("^[a-zA-Z]+") %>% 
    str_replace_all(c("Natural" = "Natural gas", 
                      "Iron" = "Iron ore",
                      "Metal" = "Metal ores",
                      "Mining" = "All mining",
                      "Tertiary" = "Higher ed.",
                      "Education" = "Higher ed."))
}

check_series_name <- function(df, nm = "\\bcoal\\b") {

  df %>%
    filter.(str_detect(series, regex(nm, ignore_case = T))) %>%
    distinct.(table_title, series, series_id, unit) %>%
    View(paste0("series containing the regex", nm))

}

ellipsis_to_vector <- function(...) {
  # Convert to a list, but with the variables still as an expression
  args_as_expression = substitute(list(...))
  # Deparse each item in the expression, turning it into a char vector
  # Why the [-1]? Because the first element in the list expression is "list"! :-)
  args_as_char_vector = sapply(args_as_expression,deparse)[-1]
  args_as_char_vector
}


quick_plot_series <- function(df, nm, ...) {


  series_vec <- ellipsis_to_vector(...)


df %>%
  filter.(series_id %in% series_vec) %>%
    mutate.(series = str_trunc(series, 20)) %>%
  ggplot() +
  geom_col(aes(year, value, fill = series)) +
  facet_wrap(~series_id) +
  labs(subtitle = nm, x = "", y = "")

}




```


```{r}
# check_series_name(industrial, "\\bcoal\\b")
# # 
# check_series_name(labour_force, "agri")
```


```{r}
# industrial %>% 
#   mutate.(year = year(date)) %>% 
# 
# quick_plot_series("disputes", A2540851X, A2540871J)

```

```{r}

# quick_plot_series(population, "population", A2060842F)


```

#### employment by sector

```{r}
recent_jobs <- labour_force %>% 
  filter.(series_id %in% c("A84602217W", "A84602523V", "A84602514T", "A84602319K")) %>% 
  mutate.(year = year,
          sector = simple_series_name(series),
    employees = value*1000, .keep = "none")

early_jobs <- early_prod_n_jobs %>% 
  select.(year, Coal = coal, `All mining` = all_mining) %>% 
  pivot_longer.(-year, names_to = "sector", values_to = "employees")
  

final_jobs <- recent_jobs %>% 
  bind_rows.(early_jobs) %>% 
  summarize.(.by = c(year, sector), 
             jobs = mean(employees, na.rm = T))
```


```{r}
final_jobs %>% 
  filter.(sector == "Coal") %>% 
  ggplot(aes(year, jobs)) +
  geom_line() +
  geom_point(size = 0.5) +
  labs(x = "", y = "Total workers") +
    scale_y_continuous(labels = unit_format(
    suffix = "K",
    scale = 1e-3,
    accuracy = 1
  )) +
  basic_add_ons


```



```{r}
final_jobs %>%
  mutate.(.by = sector,
          jobs = na.approx(jobs, na.rm = FALSE, maxgap = 20)) %>%
  left_join.(population) %>% 
  mutate.(jobs = jobs/pop) %>% 
  ggplot(aes(year, jobs, colour = sector)) +
  geom_line() +
  geom_point(size = 0.5) +
  scale_y_continuous(labels = percent_format(
    # suffix = "K",
    # scale = 1e-3,
    accuracy = 1
  )) +
  labs(x = "", y = "of total population") +
  scale_colour_manual(
    values = c(
      "Metal ores" = "darkred",
      "Coal" = "black",
      "All mining" = "blue",
      "Higher ed." = "deeppink"
    )
  )


```

#### Early production values

```{r}


early_prod_n_jobs %>% 
  filter.(year < 1960) %>% 
  select.(year, black, brown) %>% 
  pivot_longer.(-year, names_to = "type") %>% 
  ggplot() +
  geom_line(aes(year, value, colour = type)) +
  scale_colour_manual(values = c("black", "darkred")) +
  labs(x = "", y = "Imperial tons") +
  scale_y_continuous(labels = unit_format(unit = "M", accuracy = 1))




```






```{r}


late_prod_n_exports <-  fread.("coal_data/general_stats/auscoal_1961_2020_prod_n_exports_kilotonnes.csv") %>% 
  mutate.(across.(-year, ~as.numeric(str_remove(.x, ","))),
          year = as.numeric(str_extract(year, "^[0-9]{4}")),
          across.(contains("coal"), ~.x/1000))

type_order <- names(late_prod_n_exports)

late_prod_n_exports %>% 
  pivot_longer.(-year, names_to = "type") %>% 
  mutate.(type = fct_relevel(type, type_order[type_order != "year"])) %>% 
  ggplot() +
  geom_line(aes(year, value, colour = type)) +
  scale_colour_manual(values = c("black", "grey40", "blue3", "darkorchid3", "darkred")) +
  labs(x = "", y = "Metric tonnes") +
  scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-03))



```



#### Trade

```{r}
# series_id == A2717939F is the simplest most comprehensive for coal



# check_series_name(trade, "\\bnatural gas\\b")


```


```{r}
# quick_plot_series(trade, "coal", A1827829F, A2717939F)

```



```{r}
# quick_plot_series(trade, "iron", A1827853F, A1828430W)

```


```{r}

# 
# quick_plot_series(trade, "agriculture", A1828377W, A1827810F)


```

```{r}

# quick_plot_series(trade, "education", A3356356K, A2716854A, A3356359T)

# A3356360A educational services is largely empty
# A3356322L charges for the use of intellectual property

```



```{r}
# quick_plot_series(trade, "combined", A2716854A, A2717939F, A1828377W, A1828430W, A2717898W)
```




```{r}

wb_deflator <- readr::read_csv("coal_data/general_stats/WB_1961_2021_deflator_data.csv")
 
aus_deflator <- wb_deflator %>% 
  janitor::clean_names() %>% 
  filter.(country_name == "Australia") %>% 
  pivot_longer.(x1960:x2020, names_to = "year") %>% 
  mutate.(year = as.numeric(str_remove(year, "x"))) %>% 
  select.(year, deflator = value)
  

top_exports <- trade %>% 
  filter.(series_id %in% c("A2717939F", "A1828377W", "A1828430W", "A2716854A", "A2717898W", "A1828448V")) %>%
  mutate.(commodity = simple_series_name(series)) %>% 
  summarize.(.by = c(year, commodity), value = sum(value)) %>%
  left_join.(aus_deflator) %>%
  mutate.(final_value = value*10**6/(deflator/100),
          commodity = fct_reorder(commodity, final_value)) %>% 
  select.(year, commodity, final_value, deflator)

ggplot(top_exports) +
  geom_line(aes(year, final_value, colour = commodity)) +
  scale_y_continuous(labels = dollar_format(suffix = "bn", scale = 1e-9,
                                                    accuracy = 1)) +
  labs(x = "", y = "Export value (constant 2019 AUD)") +
  scale_colour_manual(values = c("Iron ore" = "firebrick2", 
                                 "Coal" = "black", 
                                 "Higher ed." = "deeppink",
                                 "Natural gas" = "blue", 
                                 "Wheat" = "goldenrod2", 
                                 "Wool" = "darkolivegreen4")) +
  geom_vline(xintercept = main_eras[3], linetype = "dashed")


```







